# This file is a template, and might need editing before it works on your project.
docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

docker-build:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master

docker-host-build:
  # Official docker image.
  image: docker:19.03.12
  stage: docker_build_dev
  services:
    - name: docker:19.03.12-dind
      # entrypoint: ["env", "-u", "DOCKER_HOST"]
      # command: ["dockerd-entrypoint.sh"]

  # variables:
  # DOCKER_DRIVER: overlay2
  # # DOCKER_HOST: tcp://docker:2375
  # DOCKER_TLS_CERTDIR: ""
  # DOCKER_HOST: tcp://localhost:2375
  # DOCKER_TLS_CERTDIR: "/certs"

  # before_script:
  #   - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY_aliyun
  # - cd src/yoyocmstemplate-aspnet-core/src/LTMCompanyName.YoyoCmsTemplate.Web.Host
  # - echo $(pwd)
  # - ls -l
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY_aliyun
    - echo "开始制作docker镜像"
    - docker build .  -t $CI_REGISTRY_aliyun/yoyosoft/52abp_pro-host  -f ./src/yoyocmstemplate-aspnet-core/src/LTMCompanyName.YoyoCmsTemplate.Web.Host/Dockerfile.host.compose

    #   - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    #   - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master
  tags:
    - ltm
